### ISSUE TITLE
Ajouter un README.md

### ISSUE THREAD

**Issue by vincentdoba** [LateralThoughts/lateralthoughts.github.com#28]
Pour l'instant : 
- On ne comprends pas très bien comment on peut modifier le site
- On ne sait pas trop quoi modifier (fichier hbs...)
- On ne sait pas trop comment mettre à jour la page de formations
- On ne sait pas trop comment tester le site en local

Ce serait bien d'avoir un readme qui explique tout cela.

**Comment by hlassiege** [comment]
tu veux dire, un README comme celui-ci : 
https://github.com/LateralThoughts/lateralthoughts.github.com/blob/dev/README.md ou celui-ci : https://github.com/LateralThoughts/lateralthoughts.github.com/blob/dev/blog/README.md (pour le blog) ?

**Comment by vincentdoba** [comment]
En effet. J'en ai profité pour rajouter la méthode pour changer les calendriers de formation.
